### ISSUE TITLE
Error: Missing value invoice_type

### ISSUE THREAD

**Issue by superfaktura** [EskelCz/superfaktura-elis-connector#2]
Skusali sme connector, ale nechce nam fungovat.
Priamo v rossum dostavame pri tlacidle "Dokoncit" chybovu hlasku:
```
SF Connector' error (invalid format of "messages": {'messages': [{'content': {}, 'type': 'warning'}]})
```

A na strane nodu:
```
Error: Missing value invoice_type
    at findValue (/app/connector.js:44:11)
    at parseData (/app/connector.js:128:33)
    at /app/connector.js:170:18
    ...
```

**Comment by EskelCz** [comment]
Zapomněl jsem to zmínit v readme, ale pokud chcete datapoint "typ faktury" , je potřeba ho přidat do schématu. Není v defaultním demo schématu od Rossum, nevím proč, i když jsem je na to upozorňoval a říkali že ho přidají.
Více o schématech v readme: https://github.com/EskelCz/superfaktura-elis-connector#schema

Pokud ho nepotřebujete, jen odeberte řádek 128.
`'type': findInvoiceType(findValue('invoice_type', content)),`

**Comment by superfaktura** [comment]
Super, s tym zakomentovanim funguje.
