### ISSUE TITLE
Wrong expense types

### ISSUE THREAD

**Issue by superfaktura** [EskelCz/superfaktura-elis-connector#5]
`invoiceTypeTable` seem to have wrong [expense types values](https://github.com/superfaktura/docs/blob/master/value-lists.md#expense-types).

Our recommendation is the following:
```
const invoiceTypeTable = {
  'tax_invoice': 'invoice', // bežná daňová faktura
  
  // remove debit_note, as it is not an expense
  // ========================
  // 'debit_note': 'invoice', // námi vystavený dobropis, opravný daňový doklad, není evidován v nákladech
  
  'credit_note': 'recieved_credit_note', // námi přijatý dobropis, opravný daňový doklad
  'proforma': 'invoice', // zálohová faktura
  'other': 'invoice' // jiné, koncept
}
```

**Comment by EskelCz** [comment]
Thanks for the detective work on this. :)
I missed the expense types and used the "invoice types" from your docs, as it seemed fitting.
Also it would have been easier to figure out if I could see the type in the actual SF interface.

**Comment by EskelCz** [comment]
Fixed in master
https://github.com/EskelCz/superfaktura-elis-connector/commit/b32e533def275e66e4745445a893e04d5bb61615
